from __future__ import annotations

"""Deprecated compatibility layer for clustering constants.

Canonical sources:
- non-UI constants: ``config.constants``
- UI labels/copy: ``app.labels``
"""

from app.statistics_constants import EXCLUDED_TABLE_PREFIXES as TABLE_EXCLUDED_PREFIXES
from app.labels import (
    CLUSTERING_AUTO_DEFAULT_EXCLUDED_FEATURES,
    CLUSTERING_DEFAULT_CLUSTER_FEATURES,
    CLUSTERING_FEATURE_METADATA,
    CLUSTERING_LOG_SCALE_FEATURES,
    CLUSTERING_MODE_LOAD_LABEL,
    CLUSTERING_MODE_PROFILE_LABEL,
    CLUSTERING_PROFILE_MODE_EXCLUDED_FEATURES,
    CLUSTERING_SAMPLING_STRATEGY_LABELS,
    CLUSTERING_WEIGHTING_STRATEGY_LABELS,
)
from config.constants import (
    CARD_TONES,
    CLUSTER_COUNT_OPTIONS,
    DEFAULT_CLUSTER_MODE_LOAD,
    DEFAULT_CLUSTER_MODE_PROFILE,
    FEATURE_SELECTION_N_INIT,
    FEATURE_SELECTION_MIN_IMPROVEMENT,
    HOPKINS_MIN_CLUSTERABLE,
    LOW_SUPPORT_TERRITORY_THRESHOLD,
    MAX_FEATURE_OPTIONS,
    MEAN_SMOOTHING_PRIOR_STRENGTH,
    MODEL_N_INIT,
    MIN_DEFAULT_FEATURE_COUNT,
    MIN_ROWS_PER_CLUSTER,
    PROFILE_MODE_SCORE_TOLERANCE,
    PROFILE_MODE_SILHOUETTE_TOLERANCE,
    RATE_SMOOTHING_PRIOR_STRENGTH,
    SAMPLE_LIMIT_OPTIONS,
    SAMPLING_STRATEGY_VALUES,
    STABILITY_RANDOM_SEEDS,
    STABILITY_RESAMPLE_RATIO,
    VOLUME_DOMINANCE_MIN_SCORE_DELTA,
    VOLUME_DOMINANCE_RATIO,
    WEIGHTING_STRATEGY_INCIDENT_LOG,
    WEIGHTING_STRATEGY_NOT_APPLICABLE,
    WEIGHTING_STRATEGY_UNIFORM,
)

SAMPLING_STRATEGY_OPTIONS = [
    {"value": value, "label": CLUSTERING_SAMPLING_STRATEGY_LABELS.get(value, value)}
    for value in SAMPLING_STRATEGY_VALUES
]
MAX_K_DIAGNOSTICS = max(CLUSTER_COUNT_OPTIONS)

DEFAULT_CLUSTER_FEATURES = list(CLUSTERING_DEFAULT_CLUSTER_FEATURES)
AUTO_DEFAULT_EXCLUDED_FEATURES = set(CLUSTERING_AUTO_DEFAULT_EXCLUDED_FEATURES)
DEFAULT_FEATURE_TARGET_COUNT = len(DEFAULT_CLUSTER_FEATURES)

DEFAULT_CLUSTER_MODE_PROFILE_LABEL = CLUSTERING_MODE_PROFILE_LABEL
DEFAULT_CLUSTER_MODE_LOAD_LABEL = CLUSTERING_MODE_LOAD_LABEL

WEIGHTING_STRATEGY_UNIFORM_LABEL = CLUSTERING_WEIGHTING_STRATEGY_LABELS[WEIGHTING_STRATEGY_UNIFORM]
WEIGHTING_STRATEGY_INCIDENT_LOG_LABEL = CLUSTERING_WEIGHTING_STRATEGY_LABELS[WEIGHTING_STRATEGY_INCIDENT_LOG]
WEIGHTING_STRATEGY_NOT_APPLICABLE_LABEL = CLUSTERING_WEIGHTING_STRATEGY_LABELS[WEIGHTING_STRATEGY_NOT_APPLICABLE]

PROFILE_MODE_EXCLUDED_FEATURES = set(CLUSTERING_PROFILE_MODE_EXCLUDED_FEATURES)
FEATURE_METADATA = CLUSTERING_FEATURE_METADATA
LOG_SCALE_FEATURES = set(CLUSTERING_LOG_SCALE_FEATURES)
