from __future__ import annotations

"""Deprecated compatibility layer for forecast-risk constants."""

from app.domain.fire_columns import (
    AREA_COLUMN,
    ARRIVAL_TIME_COLUMN_CANDIDATES,
    BUILDING_CATEGORY_COLUMN_CANDIDATES,
    BUILDING_CAUSE_COLUMN,
    CASUALTY_FLAG_COLUMN_CANDIDATES,
    CAUSE_COLUMN_CANDIDATES,
    CONSEQUENCE_COLUMN_CANDIDATES,
    DATE_COLUMN,
    DEATHS_COLUMN_CANDIDATES,
    DESTROYED_AREA_COLUMN_CANDIDATES,
    DESTROYED_BUILDINGS_COLUMN_CANDIDATES,
    DETECTION_TIME_COLUMN_CANDIDATES,
    DISTRICT_COLUMN_CANDIDATES,
    FIRE_AREA_COLUMN_CANDIDATES,
    FIRE_STATION_DISTANCE_COLUMN_CANDIDATES,
    GENERAL_CAUSE_COLUMN,
    HEATING_TYPE_COLUMN_CANDIDATES,
    INJURIES_COLUMN_CANDIDATES,
    LONG_RESPONSE_THRESHOLD_MINUTES,
    OBJECT_CATEGORY_COLUMN,
    OPEN_AREA_CAUSE_COLUMN,
    REGISTERED_DAMAGE_COLUMN_CANDIDATES,
    REPORT_TIME_COLUMN_CANDIDATES,
    RISK_CATEGORY_COLUMN_CANDIDATES,
    SETTLEMENT_TYPE_COLUMN_CANDIDATES,
    TEMPERATURE_COLUMN_CANDIDATES,
    TERRITORY_LABEL_COLUMN_CANDIDATES,
    WATER_SUPPLY_COUNT_COLUMN_CANDIDATES,
    WATER_SUPPLY_DETAILS_COLUMN_CANDIDATES,
)
from config.constants import MAX_TERRITORIES

