from __future__ import annotations

from typing import Callable, Optional

from app.labels import (
    ML_COUNT_MODEL_LABELS as L_ML_COUNT_MODEL_LABELS,
    ML_COUNT_SELECTION_RULE as L_ML_COUNT_SELECTION_RULE,
    ML_EVENT_BASELINE_METHOD_LABEL as L_ML_EVENT_BASELINE_METHOD_LABEL,
    ML_EVENT_BASELINE_ROLE_LABEL as L_ML_EVENT_BASELINE_ROLE_LABEL,
    ML_EVENT_CLASSIFIER_ROLE_LABEL as L_ML_EVENT_CLASSIFIER_ROLE_LABEL,
    ML_EVENT_HEURISTIC_METHOD_LABEL as L_ML_EVENT_HEURISTIC_METHOD_LABEL,
    ML_EVENT_HEURISTIC_ROLE_LABEL as L_ML_EVENT_HEURISTIC_ROLE_LABEL,
    ML_EVENT_MODEL_LABEL as L_ML_EVENT_MODEL_LABEL,
    ML_EVENT_SELECTION_RULE as L_ML_EVENT_SELECTION_RULE,
    ML_FEATURE_LABELS as L_ML_FEATURE_LABELS,
    ML_HISTORY_WINDOW_LABELS as L_ML_HISTORY_WINDOW_LABELS,
    ML_MODEL_NAME as L_ML_MODEL_NAME,
    ML_PREDICTION_INTERVAL_BLOCKED_CV_LABEL as L_ML_PREDICTION_INTERVAL_BLOCKED_CV_LABEL,
    ML_PREDICTION_INTERVAL_FIXED_CHRONO_LABEL as L_ML_PREDICTION_INTERVAL_FIXED_CHRONO_LABEL,
    ML_PREDICTION_INTERVAL_JACKKNIFE_PLUS_LABEL as L_ML_PREDICTION_INTERVAL_JACKKNIFE_PLUS_LABEL,
    ML_PREDICTION_INTERVAL_METHOD_LABEL as L_ML_PREDICTION_INTERVAL_METHOD_LABEL,
    ML_PREDICTION_INTERVAL_ROLLING_SPLIT_LABEL as L_ML_PREDICTION_INTERVAL_ROLLING_SPLIT_LABEL,
    ML_PREDICTIVE_BLOCK_DESCRIPTION as L_ML_PREDICTIVE_BLOCK_DESCRIPTION,
)
from config.constants import (
    CLASSIFICATION_THRESHOLD as C_CLASSIFICATION_THRESHOLD,
    COUNT_MODEL_CONTINUOUS_COLUMNS as C_COUNT_MODEL_CONTINUOUS_COLUMNS,
    COUNT_MODEL_KEYS as C_COUNT_MODEL_KEYS,
    COUNT_MODEL_SELECTION_TOLERANCE as C_COUNT_MODEL_SELECTION_TOLERANCE,
    EVENT_PROBABILITY_REASON_SATURATED_EVENT_RATE,
    EVENT_PROBABILITY_REASON_SINGLE_CLASS_EVALUATION,
    EVENT_PROBABILITY_REASON_TOO_FEW_COMPARABLE_WINDOWS,
    EVENT_RATE_SATURATION_MARGIN as C_EVENT_RATE_SATURATION_MARGIN,
    EXPLAINABLE_COUNT_MODEL_KEY as C_EXPLAINABLE_COUNT_MODEL_KEY,
    FEATURE_COLUMNS as C_FEATURE_COLUMNS,
    LOGISTIC_PARAMS as C_LOGISTIC_PARAMS,
    MAX_BACKTEST_POINTS as C_MAX_BACKTEST_POINTS,
    MAX_HISTORY_POINTS as C_MAX_HISTORY_POINTS,
    MIN_BACKTEST_POINTS as C_MIN_BACKTEST_POINTS,
    MIN_DAILY_HISTORY as C_MIN_DAILY_HISTORY,
    MIN_EVENT_CLASS_COUNT as C_MIN_EVENT_CLASS_COUNT,
    MIN_FEATURE_ROWS as C_MIN_FEATURE_ROWS,
    MIN_INTERVAL_BIN_RESIDUALS as C_MIN_INTERVAL_BIN_RESIDUALS,
    MIN_INTERVAL_CALIBRATION_WINDOWS as C_MIN_INTERVAL_CALIBRATION_WINDOWS,
    MIN_INTERVAL_EVALUATION_WINDOWS as C_MIN_INTERVAL_EVALUATION_WINDOWS,
    MIN_POSITIVE_PREDICTION as C_MIN_POSITIVE_PREDICTION,
    MIN_TEMPERATURE_COVERAGE as C_MIN_TEMPERATURE_COVERAGE,
    MIN_TEMPERATURE_NON_NULL_DAYS as C_MIN_TEMPERATURE_NON_NULL_DAYS,
    ML_CACHE_LIMIT as C_ML_CACHE_LIMIT,
    ML_CACHE_SCHEMA_VERSION,
    ML_FORECAST_DAY_OPTIONS as C_ML_FORECAST_DAY_OPTIONS,
    ML_HISTORY_WINDOWS as C_ML_HISTORY_WINDOWS,
    NEGATIVE_BINOMIAL_MIN_TRAIN_ROWS as C_NEGATIVE_BINOMIAL_MIN_TRAIN_ROWS,
    NEGATIVE_BINOMIAL_OVERDISPERSION_THRESHOLD as C_NEGATIVE_BINOMIAL_OVERDISPERSION_THRESHOLD,
    PERMUTATION_REPEATS as C_PERMUTATION_REPEATS,
    POISSON_PARAMS as C_POISSON_PARAMS,
    PREDICTION_INTERVAL_CALIBRATION_FRACTION as C_PREDICTION_INTERVAL_CALIBRATION_FRACTION,
    PREDICTION_INTERVAL_LEVEL as C_PREDICTION_INTERVAL_LEVEL,
    PREDICTION_INTERVAL_TARGET_BINS as C_PREDICTION_INTERVAL_TARGET_BINS,
    ROLLING_MIN_TRAIN_ROWS as C_ROLLING_MIN_TRAIN_ROWS,
    WARNING_INSTABILITY_MESSAGE_TOKENS,
)

MODEL_NAME = L_ML_MODEL_NAME

FORECAST_DAY_OPTIONS = list(C_ML_FORECAST_DAY_OPTIONS)
HISTORY_WINDOW_OPTIONS = [
    {"value": value, "label": L_ML_HISTORY_WINDOW_LABELS.get(value, value)}
    for value in C_ML_HISTORY_WINDOWS
]

FEATURE_LABELS = L_ML_FEATURE_LABELS

COUNT_MODEL_LABELS = L_ML_COUNT_MODEL_LABELS
EVENT_MODEL_LABEL = L_ML_EVENT_MODEL_LABEL

MIN_DAILY_HISTORY = C_MIN_DAILY_HISTORY
MIN_FEATURE_ROWS = C_MIN_FEATURE_ROWS
MIN_BACKTEST_POINTS = C_MIN_BACKTEST_POINTS
MIN_EVENT_CLASS_COUNT = C_MIN_EVENT_CLASS_COUNT
EVENT_RATE_SATURATION_MARGIN = C_EVENT_RATE_SATURATION_MARGIN
MAX_HISTORY_POINTS = C_MAX_HISTORY_POINTS
MAX_BACKTEST_POINTS = C_MAX_BACKTEST_POINTS
PERMUTATION_REPEATS = C_PERMUTATION_REPEATS
ROLLING_MIN_TRAIN_ROWS = C_ROLLING_MIN_TRAIN_ROWS
COUNT_MODEL_SELECTION_TOLERANCE = C_COUNT_MODEL_SELECTION_TOLERANCE

FEATURE_COLUMNS = list(C_FEATURE_COLUMNS)
NON_TEMPERATURE_FEATURE_COLUMNS = [column for column in FEATURE_COLUMNS if column != "temp_value"]
COUNT_MODEL_CONTINUOUS_COLUMNS = list(C_COUNT_MODEL_CONTINUOUS_COLUMNS)
COUNT_MODEL_KEYS = list(C_COUNT_MODEL_KEYS)
EXPLAINABLE_COUNT_MODEL_KEY = C_EXPLAINABLE_COUNT_MODEL_KEY
NEGATIVE_BINOMIAL_OVERDISPERSION_THRESHOLD = C_NEGATIVE_BINOMIAL_OVERDISPERSION_THRESHOLD
NEGATIVE_BINOMIAL_MIN_TRAIN_ROWS = C_NEGATIVE_BINOMIAL_MIN_TRAIN_ROWS
MIN_POSITIVE_PREDICTION = C_MIN_POSITIVE_PREDICTION
MIN_TEMPERATURE_NON_NULL_DAYS = C_MIN_TEMPERATURE_NON_NULL_DAYS
MIN_TEMPERATURE_COVERAGE = C_MIN_TEMPERATURE_COVERAGE
CLASSIFICATION_THRESHOLD = C_CLASSIFICATION_THRESHOLD
PREDICTION_INTERVAL_LEVEL = C_PREDICTION_INTERVAL_LEVEL
PREDICTION_INTERVAL_CALIBRATION_FRACTION = C_PREDICTION_INTERVAL_CALIBRATION_FRACTION
MIN_INTERVAL_CALIBRATION_WINDOWS = C_MIN_INTERVAL_CALIBRATION_WINDOWS
MIN_INTERVAL_EVALUATION_WINDOWS = C_MIN_INTERVAL_EVALUATION_WINDOWS
PREDICTION_INTERVAL_TARGET_BINS = C_PREDICTION_INTERVAL_TARGET_BINS
MIN_INTERVAL_BIN_RESIDUALS = C_MIN_INTERVAL_BIN_RESIDUALS
PREDICTION_INTERVAL_METHOD_LABEL = L_ML_PREDICTION_INTERVAL_METHOD_LABEL
PREDICTION_INTERVAL_FIXED_CHRONO_LABEL = L_ML_PREDICTION_INTERVAL_FIXED_CHRONO_LABEL
PREDICTION_INTERVAL_BLOCKED_CV_LABEL = L_ML_PREDICTION_INTERVAL_BLOCKED_CV_LABEL
PREDICTION_INTERVAL_ROLLING_SPLIT_LABEL = L_ML_PREDICTION_INTERVAL_ROLLING_SPLIT_LABEL
PREDICTION_INTERVAL_JACKKNIFE_PLUS_LABEL = L_ML_PREDICTION_INTERVAL_JACKKNIFE_PLUS_LABEL

EVENT_SELECTION_RULE = L_ML_EVENT_SELECTION_RULE
COUNT_SELECTION_RULE = L_ML_COUNT_SELECTION_RULE

EVENT_BASELINE_METHOD_LABEL = L_ML_EVENT_BASELINE_METHOD_LABEL
EVENT_BASELINE_ROLE_LABEL = L_ML_EVENT_BASELINE_ROLE_LABEL
EVENT_HEURISTIC_METHOD_LABEL = L_ML_EVENT_HEURISTIC_METHOD_LABEL
EVENT_HEURISTIC_ROLE_LABEL = L_ML_EVENT_HEURISTIC_ROLE_LABEL
EVENT_CLASSIFIER_ROLE_LABEL = L_ML_EVENT_CLASSIFIER_ROLE_LABEL

ML_PREDICTIVE_BLOCK_DESCRIPTION = L_ML_PREDICTIVE_BLOCK_DESCRIPTION

_CACHE_LIMIT = C_ML_CACHE_LIMIT
_POISSON_PARAMS = C_POISSON_PARAMS
_LOGISTIC_PARAMS = C_LOGISTIC_PARAMS

MlProgressCallback = Optional[Callable[[str, str], None]]


def _emit_progress(progress_callback: MlProgressCallback, phase: str, message: str) -> None:
    if progress_callback is None:
        return
    try:
        progress_callback(phase, message)
    except Exception:
        return
