from __future__ import annotations

from app.domain.analytics_metadata import (
    COLUMN_LABELS,
    DAMAGE_GROUP_LABEL,
    DAMAGE_GROUP_OPTION_LABEL,
    DAMAGE_GROUP_OPTION_VALUE,
    DAMAGE_OVERVIEW_LABELS,
    DAMAGE_PAIR_COLUMNS,
    DAMAGE_STANDALONE_COLUMNS,
    DASHBOARD_CACHE_TTL_SECONDS,
    DISTRIBUTION_COLUMNS,
    DISTRIBUTION_GROUPS,
    EXCLUDED_TABLE_PREFIXES,
    IMPACT_METRIC_CONFIG,
    METADATA_CACHE_TTL_SECONDS,
    PLOTLY_PALETTE,
)
from app.domain.fire_columns import (
    APARTMENTS_DAMAGED_COLUMN,
    APARTMENTS_DESTROYED_COLUMN,
    APART_HOTEL_DAMAGED_COLUMN,
    APART_HOTEL_DESTROYED_COLUMN,
    AREA_COLUMN,
    AREA_DAMAGED_COLUMN,
    AREA_DESTROYED_COLUMN,
    BIRDS_DESTROYED_COLUMN,
    BUILDINGS_DAMAGED_COLUMN,
    BUILDINGS_DESTROYED_COLUMN,
    BUILDING_CATEGORY_COLUMN,
    BUILDING_CAUSE_COLUMN,
    CAUSE_COLUMNS,
    DATE_COLUMN,
    FEED_DAMAGED_COLUMN,
    FEED_DESTROYED_COLUMN,
    FIRE_STATION_DISTANCE_COLUMN,
    GENERAL_CAUSE_COLUMN,
    GRAIN_DAMAGED_COLUMN,
    GRAIN_DESTROYED_COLUMN,
    LARGE_CATTLE_DESTROYED_COLUMN,
    OBJECT_CATEGORY_COLUMN,
    OBJECT_NAME_COLUMN,
    OPEN_AREA_CAUSE_COLUMN,
    REGISTERED_DAMAGE_COLUMN,
    RISK_CATEGORY_COLUMN,
    SMALL_CATTLE_DESTROYED_COLUMN,
    TECH_CROPS_DAMAGED_COLUMN,
    TECH_CROPS_DESTROYED_COLUMN,
    VEHICLES_DAMAGED_COLUMN,
    VEHICLES_DESTROYED_COLUMN,
)
DASHBOARD_MONTH_LABELS = {
    1: "Янв", 2: "Фев", 3: "Мар", 4: "Апр", 5: "Май", 6: "Июн",
    7: "Июл", 8: "Авг", 9: "Сен", 10: "Окт", 11: "Ноя", 12: "Дек",
}
FORECAST_MONTH_LABELS = dict(DASHBOARD_MONTH_LABELS)
FORECAST_WEEKDAY_LABELS = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"]

MONTH_LABELS = DASHBOARD_MONTH_LABELS
