from __future__ import annotations

"""Deprecated compatibility layer for access-points constants.

Canonical sources:
- non-UI constants: ``config.constants``
- domain metadata/columns: ``app.domain.*``
"""

from app.domain.access_points_metadata import (
    ACCESS_POINTS_DESCRIPTION,
    ACCESS_POINTS_TITLE,
    ACCESS_POINT_FEATURE_METADATA,
    DEFAULT_ACCESS_POINT_FEATURES,
    GENERIC_OBJECT_TOKENS,
    HIGH_RISK_THRESHOLD,
    REVIEW_RISK_THRESHOLD,
    WATCH_RISK_THRESHOLD,
)
from app.domain.fire_columns import (
    ADDRESS_COLUMN_CANDIDATES,
    ADDRESS_COMMENT_COLUMN_CANDIDATES,
    ARRIVAL_TIME_COLUMN_CANDIDATES,
    CASUALTY_FLAG_COLUMN_CANDIDATES,
    CONSEQUENCE_COLUMN_CANDIDATES,
    DATE_COLUMN,
    DEATHS_COLUMN_CANDIDATES,
    DESTROYED_AREA_COLUMN_CANDIDATES,
    DESTROYED_BUILDINGS_COLUMN_CANDIDATES,
    DETECTION_TIME_COLUMN_CANDIDATES,
    DISTRICT_COLUMN_CANDIDATES,
    FIRE_STATION_DISTANCE_COLUMN_CANDIDATES,
    INJURIES_COLUMN_CANDIDATES,
    LATITUDE_COLUMN_CANDIDATES,
    LONGITUDE_COLUMN_CANDIDATES,
    OBJECT_CATEGORY_COLUMN,
    OBJECT_CATEGORY_COLUMN_CANDIDATES,
    OBJECT_NAME_COLUMN_CANDIDATES,
    REGISTERED_DAMAGE_COLUMN_CANDIDATES,
    REPORT_TIME_COLUMN_CANDIDATES,
    SETTLEMENT_COLUMN_CANDIDATES,
    SETTLEMENT_TYPE_COLUMN_CANDIDATES,
    TERRITORY_LABEL_COLUMN_CANDIDATES,
    WATER_SUPPLY_COUNT_COLUMN_CANDIDATES,
    WATER_SUPPLY_DETAILS_COLUMN_CANDIDATES,
)
from config.constants import (
    ACCESS_POINT_LIMIT_OPTIONS,
    DEFAULT_ACCESS_POINT_LIMIT,
    LONG_RESPONSE_THRESHOLD_MINUTES,
    MAX_ACCESS_POINT_FEATURE_OPTIONS,
    MAX_INCOMPLETE_POINTS,
    MAX_NOTES,
    MIN_ACCESS_POINT_SUPPORT,
    POINT_FEATURE_COLUMNS,
    TOP_POINT_CARD_COUNT,
)
