from __future__ import annotations

"""Centralized project constants grouped by domain.

This module is the canonical source for non-UI constants.
UI labels (especially Russian copy) live in ``app.labels``.
"""

import os

# === DB / Config ===

NULL_THRESHOLD = 0.9
UNIQUE_ID_THRESHOLD = 0.99
LOW_VARIANCE_THRESHOLD = 0.0001
DOMINANT_VALUE_THRESHOLD = 0.85

MISSING_LIKE_VALUES = [
    "нет данных",
    "н/д",
    "nan",
    "none",
    "null",
    "-",
    "",
    " ",
]

PROFILING_CSV_SUFFIX = "_fires_profiling_report.csv"
PROFILING_XLSX_SUFFIX = "_fires_profiling_report.xlsx"

# === Business Rules ===

CORR_THRESHOLD = 0.9
VIF_THRESHOLD = 10
IMPORTANT_KEYWORDS = [
    "травмировать",
    "погибнуть",
    "эвакуировать",
    "ребёнок",
]

FORECASTING_FORECAST_DAY_OPTIONS = [7, 14, 30, 60]
FORECASTING_HISTORY_WINDOWS = ("all", "recent_3", "recent_5")
PRIORITY_HORIZON_DAYS = 14

ACCESS_POINT_LIMIT_OPTIONS = [10, 25, 50, 100]
DEFAULT_ACCESS_POINT_LIMIT = 25
MIN_ACCESS_POINT_SUPPORT = 3
LONG_RESPONSE_THRESHOLD_MINUTES = 20.0
TOP_POINT_CARD_COUNT = 5
MAX_INCOMPLETE_POINTS = 6
MAX_NOTES = 7
MAX_ACCESS_POINT_FEATURE_OPTIONS = 10
POINT_FEATURE_COLUMNS = (
    "incident_count",
    "incidents_per_year",
    "average_response_minutes",
    "response_coverage_share",
    "long_arrival_share",
    "average_distance_km",
    "distance_coverage_share",
    "no_water_share",
    "water_coverage_share",
    "water_unknown_share",
    "severe_share",
    "victim_share",
    "major_damage_share",
    "night_share",
    "heating_share",
    "rural_share",
    "rural_flag",
    "low_support",
    "support_weight",
)

CLUSTER_COUNT_OPTIONS = [2, 3, 4, 5, 6]
SAMPLE_LIMIT_OPTIONS = [50, 100, 200, 500, 1000]
CARD_TONES = ["group", "area", "table", "fire", "muted"]
MAX_FEATURE_OPTIONS = 12
MIN_ROWS_PER_CLUSTER = 5
MIN_DEFAULT_FEATURE_COUNT = 4
FEATURE_SELECTION_MIN_IMPROVEMENT = 0.0025
DEFAULT_CLUSTER_MODE_PROFILE = "territory_profile"
DEFAULT_CLUSTER_MODE_LOAD = "load_profile"
CLUSTERING_RANDOM_STATE = 42
WEIGHTING_STRATEGY_UNIFORM = "uniform"
WEIGHTING_STRATEGY_INCIDENT_LOG = "incident_log"
WEIGHTING_STRATEGY_NOT_APPLICABLE = "not_applicable"
PROFILE_MODE_SCORE_TOLERANCE = 0.01
PROFILE_MODE_SILHOUETTE_TOLERANCE = 0.015
VOLUME_DOMINANCE_RATIO = 1.35
VOLUME_DOMINANCE_MIN_SCORE_DELTA = 0.01
RATE_SMOOTHING_PRIOR_STRENGTH = 3.0
MEAN_SMOOTHING_PRIOR_STRENGTH = 2.0
LOW_SUPPORT_TERRITORY_THRESHOLD = 2
ACTION_COMPONENT_SCORE_THRESHOLD = 55
ACTION_WATER_SCORE_THRESHOLD = 50
ACTION_RISK_SCORE_HIGH = 70
RANKING_GAP_MAJOR = 4.0
RANKING_GAP_MODERATE = 1.5
RANKING_GAP_CLOSE_TO_TOP = 2.0
RANKING_GAP_UPPER_GROUP = 6.0
RANKING_CONFIDENCE_HIGH_THRESHOLD = 82
RANKING_CONFIDENCE_WORKING_THRESHOLD = 64
RANKING_CONFIDENCE_MODERATE_THRESHOLD = 46
RANKING_LOWER_POSITION_CUTOFF = 3
HISTORY_RECENCY_WEIGHT_MIN = 0.25
HISTORY_MAX_AGE_SPAN_DAYS = 210.0
HISTORY_MONTH_ALIGNMENT_BOOST = 0.40
HISTORY_WEEKDAY_ALIGNMENT_BOOST = 0.18
HISTORY_RECENT_WINDOW_DAYS = 90
PASSPORT_PARTIAL_FEATURE_WEIGHT = 0.55
PASSPORT_CRITICAL_GAP_PENALTY = 8.0
PASSPORT_MAX_CRITICAL_GAPS = 3
PASSPORT_HIGH_CONFIDENCE_THRESHOLD = 80
PASSPORT_WORKING_CONFIDENCE_THRESHOLD = 60
PASSPORT_MODERATE_CONFIDENCE_THRESHOLD = 40
VALIDATION_MIN_TRAINING_DAYS = 180
VALIDATION_TRAINING_HORIZON_MULTIPLIER = 6
VALIDATION_WINDOW_STEP_MIN_DAYS = 30
VALIDATION_MAX_CUTOFFS = 12
VALIDATION_OBJECTIVE_TOP1_WEIGHT = 0.24
VALIDATION_OBJECTIVE_CAPTURE_WEIGHT = 0.31
VALIDATION_OBJECTIVE_PRECISION_WEIGHT = 0.20
VALIDATION_OBJECTIVE_NDCG_WEIGHT = 0.25
VALIDATION_STATUS_STABLE_WINDOWS = 4
VALIDATION_STATUS_STABLE_CAPTURE = 0.60
VALIDATION_STATUS_STABLE_NDCG = 0.62
VALIDATION_STATUS_WORKING_WINDOWS = 3
VALIDATION_STATUS_WORKING_CAPTURE = 0.45
VALIDATION_STATUS_WORKING_NDCG = 0.48
FORECAST_RISK_RANKING_K = 3  # k used for top-k ranking evaluation metrics
NDCG_RELEVANCE_CAP = 5.0  # maximum relevance grade per territory in NDCG computation
CALIBRATION_FOCUS_DEFAULT_WEIGHT = 0.18
CALIBRATION_FOCUS_TARGET_WEIGHT = 0.46
CALIBRATION_SHIFT_SMALL = 0.04
CALIBRATION_SHIFT_LARGE = 0.08
PROBABILITY_SCALE_THRESHOLD = 1.5
PROBABILITY_MAX_DOUBLE_PERCENT = 10000.0
FORMAT_SIGNED_PERCENT_ZERO_THRESHOLD = 0.05
STABILITY_RESAMPLE_RATIO = 0.8
STABILITY_RANDOM_SEEDS = [7, 21, 42, 84, 126]
CLUSTER_SHAPE_MICROCLUSTER_MIN_SIZE = 3
SUBSET_MIN_NON_NULL_RATIO = 0.6
SUBSET_MIN_NON_NULL_ABSOLUTE = 2
HOPKINS_MIN_ROW_COUNT = 10
HOPKINS_SAMPLE_DIVISOR = 10
HOPKINS_MAX_SAMPLE_SIZE = 50
STABILITY_RESAMPLE_MIN_ROWS = 8
STABILITY_RESAMPLE_SIZE_MULTIPLIER = 2
STABILITY_MIN_OVERLAP = 4
LOG_TRANSFORM_SKEW_THRESHOLD = 1.0
HOPKINS_MIN_CLUSTERABLE = 0.6
FEATURE_SELECTION_N_INIT = 20
MODEL_N_INIT = 40
GAP_STAT_MAX_WORKERS = min(4, (os.cpu_count() or 1))
GAP_STAT_N_REFERENCES = 10
CLUSTER_QUALITY_SILHOUETTE_WEIGHT = 0.55
CLUSTER_QUALITY_INVERSE_DB_WEIGHT = 0.20
CLUSTER_QUALITY_SCALED_CH_WEIGHT = 0.15
CLUSTER_QUALITY_BALANCE_WEIGHT = 0.10
CLUSTER_SHAPE_MICROCLUSTER_DENSITY_THRESHOLD = 0.03
CLUSTER_SHAPE_BALANCE_WARNING_THRESHOLD = 0.18
CLUSTER_SHAPE_MICROCLUSTER_PENALTY_MAX = 0.14
CLUSTER_SHAPE_MICROCLUSTER_PENALTY_BASE = 0.04
CLUSTER_SHAPE_MICROCLUSTER_PENALTY_SCALE = 0.10
CLUSTER_SHAPE_IMBALANCE_PENALTY_MAX = 0.10
CLUSTER_SHAPE_IMBALANCE_PENALTY_SCALE = 0.08
CLUSTER_SILHOUETTE_GOOD_THRESHOLD = 0.25
CLUSTER_DAVIES_BOULDIN_GOOD_THRESHOLD = 1.30
CLUSTER_STABILITY_ARI_GOOD_THRESHOLD = 0.45
CLUSTER_BALANCE_RATIO_MIN_THRESHOLD = 0.10
CLUSTER_STABILITY_ARI_DIVERGENCE_THRESHOLD = 0.15
CLUSTER_BALANCE_RATIO_CRITICAL_THRESHOLD = 0.12
CLUSTER_SILHOUETTE_STRONG_THRESHOLD = 0.40
CLUSTER_DAVIES_BOULDIN_STRONG_THRESHOLD = 1.00
CLUSTER_STABILITY_ARI_STRONG_THRESHOLD = 0.70
CLUSTER_BALANCE_RATIO_STRONG_THRESHOLD = 0.18

MAX_TERRITORIES = 12

# === Scoring risk formula constants ===

# Bounds for base_fire_signal (exponential decay of incident rate)
BASE_FIRE_SIGNAL_MIN = 0.08
BASE_FIRE_SIGNAL_MAX = 0.72

# Multiplier to scale expected Poisson parameter relative to base signal
FIRE_EXPECTED_VALUE_SCALE = 0.72

# Fallback floor for fire probability from history pressure
FIRE_PROBABILITY_FLOOR_HISTORY_WEIGHT = 0.52
FIRE_PROBABILITY_FLOOR_BASE = 0.22
FIRE_PROBABILITY_FLOOR_MAX = 0.94

# Seasonal alignment blend weights (month vs weekday contribution, must sum to 1.0)
SEASONAL_MONTH_WEIGHT = 0.62
SEASONAL_WEEKDAY_WEIGHT = 0.38

# Fire probability clamp bounds
FIRE_PROBABILITY_CLAMP_MIN = 0.02
FIRE_PROBABILITY_CLAMP_MAX = 0.995

# Distance score normalization (km)
DISTANCE_SCORE_MIN_KM = 6.0
DISTANCE_SCORE_RANGE_KM = 24.0

# Response pressure normalization (minutes)
RESPONSE_PRESSURE_TARGET_MIN = 12.0
RESPONSE_PRESSURE_NORMALIZATION_RANGE_MIN = 18.0

# Fallback response pressure when avg_response is unknown
RESPONSE_PRESSURE_UNKNOWN_FALLBACK = 0.42
RESPONSE_PRESSURE_DISTANCE_SCALE = 0.72

# Arrival probability component weights (must sum to 1.0)
ARRIVAL_PROB_LONG_ARRIVAL_WEIGHT = 0.26
ARRIVAL_PROB_RESPONSE_WEIGHT = 0.19
ARRIVAL_PROB_TRAVEL_WEIGHT = 0.23
ARRIVAL_PROB_COVERAGE_WEIGHT = 0.21
ARRIVAL_PROB_ZONE_WEIGHT = 0.11
ARRIVAL_PROB_CLAMP_MIN = 0.03
ARRIVAL_PROB_CLAMP_MAX = 0.98
LONG_ARRIVAL_FALLBACK_DISTANCE_SCALE = 0.55
LONG_ARRIVAL_FALLBACK_MIN = 0.05
LONG_ARRIVAL_FALLBACK_MAX = 0.75

# Priority-label thresholds for component-driven escalation.
PRIORITY_ARRIVAL_IMMEDIATE_THRESHOLD = 65
PRIORITY_WATER_IMMEDIATE_THRESHOLD = 55
PRIORITY_RURAL_ARRIVAL_THRESHOLD = 62
PRIORITY_RURAL_FIRE_THRESHOLD = 60
PRIORITY_ANY_COMPONENT_TARGETED = 60
RANKING_HISTORY_SUPPORT_DIVISOR = 8.0
RANKING_MARGIN_TOP_DIVISOR = 8.0
RANKING_MARGIN_GAP_DIVISOR = 12.0
RANKING_LOCAL_MARGIN_WEIGHT = 0.58
RANKING_LOCAL_HISTORY_WEIGHT = 0.42
RANKING_LOCAL_SUPPORT_CLAMP_MIN = 0.15
RANKING_CONF_PASSPORT_WEIGHT = 0.42
RANKING_CONF_OBJECTIVE_WEIGHT = 0.38
RANKING_CONF_LOCAL_WEIGHT = 0.20
RANKING_CONF_VALIDATED_CLAMP_MIN = 0.18
RANKING_CONF_VALIDATED_CLAMP_MAX = 0.96
RANKING_CONF_FALLBACK_PASSPORT_WEIGHT = 0.67
RANKING_CONF_FALLBACK_LOCAL_WEIGHT = 0.33
RANKING_CONF_FALLBACK_CLAMP_MIN = 0.16
RANKING_CONF_FALLBACK_CLAMP_MAX = 0.88
RANKING_CONF_TOP_BOOST = 0.03
RANKING_CONF_LOWER_PENALTY = 0.04
RANKING_CONF_LOWER_CLAMP_MIN = 0.16
RANKING_CONF_LOWER_CLAMP_MAX = 0.92

# Tanker dependency blend weights (must sum to 1.0)
TANKER_DEPENDENCY_DISTANCE_WEIGHT = 0.58
TANKER_DEPENDENCY_RESPONSE_WEIGHT = 0.42

# Water deficit probability blend weights (must sum to 1.0)
WATER_DEFICIT_GAP_WEIGHT = 0.76
WATER_DEFICIT_TANKER_WEIGHT = 0.24
WATER_DEFICIT_CLAMP_MIN = 0.02
WATER_DEFICIT_CLAMP_MAX = 0.99
WATER_GAP_UNKNOWN_DEFAULT = 0.38

# Casualty pressure scaling factor (converts victim rate to 0-1 pressure)
CASUALTY_PRESSURE_SCALE = 1.8

# Damage pressure weights (damage_rate vs severe_rate blend)
DAMAGE_PRESSURE_DAMAGE_WEIGHT = 0.70
DAMAGE_PRESSURE_SEVERE_WEIGHT = 0.30

# Severe probability component weights (must sum to 1.0)
SEVERE_PROB_SEVERE_RATE_WEIGHT = 0.46
SEVERE_PROB_CASUALTY_WEIGHT = 0.26
SEVERE_PROB_DAMAGE_WEIGHT = 0.18
SEVERE_PROB_RISK_FACTOR_WEIGHT = 0.10
SEVERE_PROB_CLAMP_MIN = 0.02
SEVERE_PROB_CLAMP_MAX = 0.98

# Default risk_factor when no risk_score_count data available
DEFAULT_RISK_FACTOR = 0.26
RISK_SCORE_CLAMP_MIN = 1.0
RISK_SCORE_CLAMP_MAX = 99.0
BAR_WIDTH_MIN_RISK = 10
BAR_WIDTH_MIN_COMPONENT = 12
BAR_WIDTH_MAX = 100

# Cluster risk score thresholds
CLUSTER_RISK_HIGH_THRESHOLD = 0.65
CLUSTER_RISK_MEDIUM_THRESHOLD = 0.35

MIN_TEMPERATURE_NON_NULL_DAYS = 30
MIN_TEMPERATURE_COVERAGE = 0.20
GEO_LOOKBACK_DAYS = 180
MAX_GEO_CHART_POINTS = 40
MAX_GEO_HOTSPOTS = 8
MAX_GEO_DISTRICTS = 6
GEO_RECENCY_WEIGHT_MIN = 0.2
GEO_MONTH_WEIGHT_BOOST = 0.35
GEO_WEEKDAY_WEIGHT_BOOST = 0.20
GEO_LOG_INCIDENTS_SCALE = 0.22
GEO_FRESHNESS_BASE = 0.85
GEO_FRESHNESS_SCALE = 0.15
GEO_CONFIDENCE_MAX = 96.0
GEO_CONFIDENCE_BASE = 42.0
GEO_CONFIDENCE_INCIDENTS_SCALE = 7.0
GEO_CONFIDENCE_FRESHNESS_CAP = 25.0
GEO_CONFIDENCE_FRESHNESS_DECAY = 0.18
GEO_MARKER_SIZE_MIN = 12.0
GEO_MARKER_SIZE_MAX = 32.0
GEO_MARKER_SIZE_BASE = 10.0
GEO_MARKER_SIZE_RISK_DIVISOR = 4.5
GEO_MARKER_SIZE_LOG_SCALE = 3.0
GEO_CELL_SPAN_XS = 0.35
GEO_CELL_SPAN_SM = 1.20
GEO_CELL_SPAN_MD = 3.00
GEO_CELL_SPAN_LG = 8.00
GEO_CELL_SIZE_XS = 0.05
GEO_CELL_SIZE_SM = 0.08
GEO_CELL_SIZE_MD = 0.12
GEO_CELL_SIZE_LG = 0.20
GEO_CELL_SIZE_XL_MAX = 0.60
GEO_CELL_SPAN_DIVISOR = 18.0
GEO_RISK_CRITICAL_THRESHOLD = 80
GEO_RISK_HIGH_THRESHOLD = 60
GEO_RISK_MEDIUM_THRESHOLD = 35

# Explainable logistics thresholds.
SERVICE_TIME_TARGET_MINUTES = 20.0
SERVICE_DISTANCE_TARGET_KM = 12.0
CORE_SERVICE_TIME_MINUTES = 14.0

# === Logistics travel-time model constants ===

# Vehicle speed assumptions (km/h) by territory type
LOGISTICS_RURAL_SPEED_KMH = 34.0
LOGISTICS_URBAN_SPEED_KMH = 42.0
LOGISTICS_MINIMUM_SPEED_KMH = 22.0

# Night-time speed reduction coefficient per unit of night_share
LOGISTICS_NIGHT_SPEED_REDUCTION = 0.14

# Blend weights for observed vs distance-estimated travel time
LOGISTICS_RESPONSE_OBSERVED_WEIGHT_HIGH = 0.72   # >= 3 observations
LOGISTICS_RESPONSE_OBSERVED_WEIGHT_LOW = 0.58    # < 3 observations
LOGISTICS_RESPONSE_OBSERVATIONS_THRESHOLD = 3

# Fallback travel-time when neither response nor distance is available
LOGISTICS_FALLBACK_TRAVEL_RURAL_MIN = 24.0
LOGISTICS_FALLBACK_TRAVEL_URBAN_MIN = 18.0

# === ML ===

ML_FORECAST_DAY_OPTIONS = [7, 14, 30]
ML_HISTORY_WINDOWS = ("all", "recent_3", "recent_5")

MIN_DAILY_HISTORY = 60
MIN_FEATURE_ROWS = 24
MIN_BACKTEST_POINTS = 8
MIN_EVENT_CLASS_COUNT = 8
EVENT_RATE_SATURATION_MARGIN = 0.05
MAX_HISTORY_POINTS = 900
MAX_BACKTEST_POINTS = 45
PERMUTATION_REPEATS = 8
ROLLING_MIN_TRAIN_ROWS = 28
COUNT_MODEL_SELECTION_TOLERANCE = 0.05
BASELINE_RECENT_WINDOW_DAYS = 28
BASELINE_WEEKDAY_TAIL = 8
BASELINE_WEEKDAY_MIN_SAMPLES = 3
BASELINE_WEEKDAY_WEIGHT = 0.6
BASELINE_RECENT_WEIGHT = 0.4
COUNT_PREDICTION_CAP_FLOOR = 250.0
COUNT_PREDICTION_CAP_SUPPORT_MULTIPLIER = 20.0
COUNT_PREDICTION_CAP_SUPPORT_OFFSET = 50.0
NEGATIVE_BINOMIAL_ALPHA_DEFAULT = 0.25
NEGATIVE_BINOMIAL_ALPHA_FLOOR = 1e-4
NEGATIVE_BINOMIAL_ALPHA_MAX = 5.0
TREND_WARNING_RELATIVE_THRESHOLD = 0.30

FEATURE_COLUMNS = [
    "temp_value",
    "weekday",
    "month",
    "lag_1",
    "lag_7",
    "lag_14",
    "rolling_7",
    "rolling_28",
]
COUNT_MODEL_CONTINUOUS_COLUMNS = [
    "temp_value",
    "lag_1",
    "lag_7",
    "lag_14",
    "rolling_7",
    "rolling_28",
]
COUNT_MODEL_KEYS = ["poisson", "negative_binomial"]
EXPLAINABLE_COUNT_MODEL_KEY = "poisson"
NEGATIVE_BINOMIAL_OVERDISPERSION_THRESHOLD = 1.35
NEGATIVE_BINOMIAL_MIN_TRAIN_ROWS = 56
MIN_POSITIVE_PREDICTION = 1e-6
CLASSIFICATION_THRESHOLD = 0.5

PREDICTION_INTERVAL_LEVEL = 0.90
PREDICTION_INTERVAL_CALIBRATION_FRACTION = 0.6
MIN_INTERVAL_CALIBRATION_WINDOWS = 6
MIN_INTERVAL_EVALUATION_WINDOWS = 4
PREDICTION_INTERVAL_TARGET_BINS = 3
MIN_INTERVAL_BIN_RESIDUALS = 2

EVENT_PROBABILITY_REASON_TOO_FEW_COMPARABLE_WINDOWS = "too_few_comparable_windows"
EVENT_PROBABILITY_REASON_SINGLE_CLASS_EVALUATION = "single_class_evaluation"
EVENT_PROBABILITY_REASON_SATURATED_EVENT_RATE = "saturated_event_rate"

WARNING_INSTABILITY_MESSAGE_TOKENS = (
    "perfect separation",
    "perfect prediction",
    "parameter may not be identified",
    "parameters are not identified",
    "failed to converge",
    "did not converge",
    "singular",
    "hessian",
)

ML_CACHE_SCHEMA_VERSION = 4
ML_CACHE_LIMIT = 128
ML_TRAINING_ARTIFACT_CACHE_LIMIT = 32

POISSON_PARAMS = {
    "alpha": 0.40,
    "max_iter": 2000,
}

LOGISTIC_PARAMS = {
    "solver": "liblinear",
    "max_iter": 500,
    "class_weight": "balanced",
    "random_state": CLUSTERING_RANDOM_STATE,
}


def _validate_weight_group(name: str, *values: float) -> None:
    total = sum(values)
    if abs(total - 1.0) > 1e-9:
        raise ValueError(f"Weight group '{name}' must sum to 1.0, got {total:.6f}")


_validate_weight_group(
    "SEASONAL_*_WEIGHT",
    SEASONAL_MONTH_WEIGHT,
    SEASONAL_WEEKDAY_WEIGHT,
)
_validate_weight_group(
    "ARRIVAL_PROB_*_WEIGHT",
    ARRIVAL_PROB_LONG_ARRIVAL_WEIGHT,
    ARRIVAL_PROB_RESPONSE_WEIGHT,
    ARRIVAL_PROB_TRAVEL_WEIGHT,
    ARRIVAL_PROB_COVERAGE_WEIGHT,
    ARRIVAL_PROB_ZONE_WEIGHT,
)
_validate_weight_group(
    "TANKER_DEPENDENCY_*_WEIGHT",
    TANKER_DEPENDENCY_DISTANCE_WEIGHT,
    TANKER_DEPENDENCY_RESPONSE_WEIGHT,
)
_validate_weight_group(
    "WATER_DEFICIT_*_WEIGHT",
    WATER_DEFICIT_GAP_WEIGHT,
    WATER_DEFICIT_TANKER_WEIGHT,
)
_validate_weight_group(
    "DAMAGE_PRESSURE_*_WEIGHT",
    DAMAGE_PRESSURE_DAMAGE_WEIGHT,
    DAMAGE_PRESSURE_SEVERE_WEIGHT,
)
_validate_weight_group(
    "SEVERE_PROB_*_WEIGHT",
    SEVERE_PROB_SEVERE_RATE_WEIGHT,
    SEVERE_PROB_CASUALTY_WEIGHT,
    SEVERE_PROB_DAMAGE_WEIGHT,
    SEVERE_PROB_RISK_FACTOR_WEIGHT,
)
_validate_weight_group(
    "VALIDATION_OBJECTIVE_*_WEIGHT",
    VALIDATION_OBJECTIVE_TOP1_WEIGHT,
    VALIDATION_OBJECTIVE_CAPTURE_WEIGHT,
    VALIDATION_OBJECTIVE_PRECISION_WEIGHT,
    VALIDATION_OBJECTIVE_NDCG_WEIGHT,
)

# === Narrative Thresholds ===
NARRATIVE_HEATING_SHARE_THRESHOLD = 0.45
NARRATIVE_COVERAGE_DEFICIT_THRESHOLD = 0.45
NARRATIVE_DISTANCE_REMOTE_KM = 15.0
NARRATIVE_COMPONENT_SCORE_FLOOR = 38.0
DEFAULT_DISTANCE_KM_BASELINE = 12.0
NARRATIVE_HISTORY_PRESSURE_HIGH = 0.65
NARRATIVE_RECENCY_PRESSURE_HIGH = 0.60
NARRATIVE_SEASONAL_ALIGNMENT_HIGH = 0.55
NARRATIVE_SCORE_LOW_THRESHOLD = 35
NARRATIVE_SEVERE_RATE_HIGH = 0.25
NARRATIVE_VICTIMS_RATE_MIN = 0.08
NARRATIVE_DAMAGE_RATE_HIGH = 0.30
NARRATIVE_RISK_FACTOR_HIGH = 0.56
NARRATIVE_LONG_ARRIVAL_HIGH = 0.25
NARRATIVE_LOGISTICS_PRIORITY_HIGH = 55
NARRATIVE_TANKER_DEPENDENCY_HIGH = 0.55
NARRATIVE_HEATING_SHARE_DRIVER = 0.50

# === Logistics explainability constants ===

# Coverage blending weights by available evidence type.
COVERAGE_BLEND_FULL_RESPONSE = 0.50
COVERAGE_BLEND_FULL_TRAVEL = 0.30
COVERAGE_BLEND_FULL_DISTANCE = 0.20
COVERAGE_BLEND_RESPONSE_ONLY_RESPONSE = 0.72
COVERAGE_BLEND_RESPONSE_ONLY_TRAVEL = 0.28
COVERAGE_BLEND_DISTANCE_ONLY_TRAVEL = 0.62
COVERAGE_BLEND_DISTANCE_ONLY_DISTANCE = 0.38

# Logistics priority score component weights.
LOGISTICS_PRIORITY_TRAVEL_WEIGHT = 0.44
LOGISTICS_PRIORITY_COVERAGE_WEIGHT = 0.34
LOGISTICS_PRIORITY_ZONE_WEIGHT = 0.14
LOGISTICS_PRIORITY_DISTANCE_WEIGHT = 0.08
_validate_weight_group(
    "COVERAGE_BLEND_FULL_*",
    COVERAGE_BLEND_FULL_RESPONSE,
    COVERAGE_BLEND_FULL_TRAVEL,
    COVERAGE_BLEND_FULL_DISTANCE,
)
_validate_weight_group(
    "COVERAGE_BLEND_RESPONSE_ONLY_*",
    COVERAGE_BLEND_RESPONSE_ONLY_RESPONSE,
    COVERAGE_BLEND_RESPONSE_ONLY_TRAVEL,
)
_validate_weight_group(
    "COVERAGE_BLEND_DISTANCE_ONLY_*",
    COVERAGE_BLEND_DISTANCE_ONLY_TRAVEL,
    COVERAGE_BLEND_DISTANCE_ONLY_DISTANCE,
)
_validate_weight_group(
    "LOGISTICS_PRIORITY_*_WEIGHT",
    LOGISTICS_PRIORITY_TRAVEL_WEIGHT,
    LOGISTICS_PRIORITY_COVERAGE_WEIGHT,
    LOGISTICS_PRIORITY_ZONE_WEIGHT,
    LOGISTICS_PRIORITY_DISTANCE_WEIGHT,
)

# Service-zone thresholds by travel time and coverage.
SERVICE_ZONE_CORE_COVERAGE_MIN = 0.72
SERVICE_ZONE_NORM_COVERAGE_MIN = 0.55
SERVICE_ZONE_TENSION_TIME_MAX = 28.0
SERVICE_ZONE_TENSION_COVERAGE_MIN = 0.35

# Coverage label thresholds.
COVERAGE_LABEL_STABLE_MIN = 0.75
COVERAGE_LABEL_BORDER_MIN = 0.55
COVERAGE_LABEL_TENSION_MIN = 0.35

# Logistics priority label thresholds.
LOGISTICS_PRIORITY_CRITICAL_MIN = 70.0
LOGISTICS_PRIORITY_HIGH_MIN = 50.0
LOGISTICS_PRIORITY_TARGETED_MIN = 35.0

# Explainability fallback and distance-coverage shaping constants.
COVERAGE_FALLBACK_RURAL = 0.46
COVERAGE_FALLBACK_URBAN = 0.58
DISTANCE_COVERAGE_LOW_MULTIPLIER = 1.3
DISTANCE_COVERAGE_HIGH_MULTIPLIER = 1.5

# === Access Point Scoring ===
ACCESS_POINT_CODE_DISTANCE = "DISTANCE_TO_STATION"
ACCESS_POINT_CODE_RESPONSE = "RESPONSE_TIME"
ACCESS_POINT_CODE_LONG_ARRIVAL = "LONG_ARRIVAL_SHARE"
ACCESS_POINT_CODE_WATER = "NO_WATER"
ACCESS_POINT_CODE_SEVERITY = "SEVERE_CONSEQUENCES"
ACCESS_POINT_CODE_RECURRENCE = "REPEAT_FIRES"
ACCESS_POINT_CODE_NIGHT = "NIGHT_PROFILE"
ACCESS_POINT_CODE_HEATING = "HEATING_SEASON"
ACCESS_POINT_FACTOR_WEIGHTS = {
    ACCESS_POINT_CODE_DISTANCE: 16.0,
    ACCESS_POINT_CODE_RESPONSE: 14.0,
    ACCESS_POINT_CODE_LONG_ARRIVAL: 10.0,
    ACCESS_POINT_CODE_WATER: 12.0,
    ACCESS_POINT_CODE_SEVERITY: 18.0,
    ACCESS_POINT_CODE_RECURRENCE: 14.0,
    ACCESS_POINT_CODE_NIGHT: 6.0,
    ACCESS_POINT_CODE_HEATING: 4.0,
}
ACCESS_POINT_SEVERITY_SEVERE_WEIGHT = 0.58
ACCESS_POINT_SEVERITY_VICTIM_WEIGHT = 0.24
ACCESS_POINT_SEVERITY_DAMAGE_WEIGHT = 0.18
ACCESS_POINT_RECURRENCE_FREQUENCY_WEIGHT = 0.70
ACCESS_POINT_RECURRENCE_INCIDENTS_WEIGHT = 0.30
ACCESS_POINT_UNCERTAINTY_ARRIVAL_WEIGHT = 0.35
ACCESS_POINT_UNCERTAINTY_WATER_WEIGHT = 0.30
ACCESS_POINT_UNCERTAINTY_DISTANCE_WEIGHT = 0.20
ACCESS_POINT_UNCERTAINTY_SUPPORT_WEIGHT = 0.15
ACCESS_POINT_UNCERTAINTY_PENALTY_MAX = 6.0
ACCESS_POINT_CRITICAL_THRESHOLD = 75.0
ACCESS_POINT_HIGH_THRESHOLD = 55.0
ACCESS_POINT_MEDIUM_THRESHOLD = 30.0
_validate_weight_group(
    "ACCESS_POINT_SEVERITY_*_WEIGHT",
    ACCESS_POINT_SEVERITY_SEVERE_WEIGHT,
    ACCESS_POINT_SEVERITY_VICTIM_WEIGHT,
    ACCESS_POINT_SEVERITY_DAMAGE_WEIGHT,
)
_validate_weight_group(
    "ACCESS_POINT_RECURRENCE_*_WEIGHT",
    ACCESS_POINT_RECURRENCE_FREQUENCY_WEIGHT,
    ACCESS_POINT_RECURRENCE_INCIDENTS_WEIGHT,
)
_validate_weight_group(
    "ACCESS_POINT_UNCERTAINTY_*_WEIGHT",
    ACCESS_POINT_UNCERTAINTY_ARRIVAL_WEIGHT,
    ACCESS_POINT_UNCERTAINTY_WATER_WEIGHT,
    ACCESS_POINT_UNCERTAINTY_DISTANCE_WEIGHT,
    ACCESS_POINT_UNCERTAINTY_SUPPORT_WEIGHT,
)
